{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:OCC.Display.backend:backend loaded: qt-pyqt5\n",
      "INFO:OCC.Display.SimpleGui:GUI backend set to: qt-pyqt5\n"
     ]
    }
   ],
   "source": [
    "from __future__ import print_function\n",
    "\n",
    "from OCC.gp import gp_Pnt, gp_Ax2, gp_Dir, gp_Circ\n",
    "from OCC.GeomAPI import GeomAPI_PointsToBSpline\n",
    "from OCC.TColgp import TColgp_Array1OfPnt\n",
    "from OCC.BRepBuilderAPI import BRepBuilderAPI_MakeEdge, BRepBuilderAPI_MakeWire, BRepBuilderAPI_MakeFace\n",
    "from OCC.BRepOffsetAPI import BRepOffsetAPI_MakePipe\n",
    "\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "\n",
    "\n",
    "def pipe(point1, point2):\n",
    "    makeWire = BRepBuilderAPI_MakeWire()\n",
    "    edge = BRepBuilderAPI_MakeEdge(point1, point2).Edge()\n",
    "    makeWire.Add(edge)\n",
    "    makeWire.Build()\n",
    "    wire = makeWire.Wire()\n",
    "\n",
    "    dir = gp_Dir(point2.X() - point1.X(), point2.Y() - point1.Y(), point2.Z() - point1.Z())\n",
    "    circle = gp_Circ(gp_Ax2(point1,dir), 0.2)\n",
    "    profile_edge = BRepBuilderAPI_MakeEdge(circle).Edge()\n",
    "    profile_wire = BRepBuilderAPI_MakeWire(profile_edge).Wire()\n",
    "    profile_face = BRepBuilderAPI_MakeFace(profile_wire).Face()\n",
    "    pipe = BRepOffsetAPI_MakePipe(wire, profile_face).Shape()\n",
    "#    display.DisplayShape(pipe, update=True)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    pipe(gp_Pnt(0,0,0), gp_Pnt(0,0,1))\n",
    "    pipe(gp_Pnt(0,0,1), gp_Pnt(0,1,2))     \n",
    "    pipe(gp_Pnt(0,1,2), gp_Pnt(0,2,2))\n",
    "#    start_display()\n",
    "    \n",
    "from OCC.BRepPrimAPI import BRepPrimAPI_MakeSphere\n",
    "\n",
    "def sphere(centre, radius):\n",
    "    sphere = BRepPrimAPI_MakeSphere (centre, radius).Shape()\n",
    "#    display.DisplayShape(sphere, update=True)\n",
    "\n",
    "def pipe(point1, point2):\n",
    "    ...\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    pipe(gp_Pnt(0,0,0), gp_Pnt(0,0,1))\n",
    "    sphere(gp_Pnt(0,0,1), 0.2)\n",
    "    pipe(gp_Pnt(0,0,1), gp_Pnt(0,1,2))     \n",
    "    sphere(gp_Pnt(0,1,2), 0.2)\n",
    "    pipe(gp_Pnt(0,1,2), gp_Pnt(0,2,2))\n",
    "#    start_display()\n",
    "    \n",
    "    \n",
    "from OCC.ChFi2d import ChFi2d_AnaFilletAlgo\n",
    "\n",
    "def filletEdges(ed1, ed2):\n",
    "    radius = 0.3\n",
    "    f = ChFi2d_AnaFilletAlgo()\n",
    "    f.Init(ed1,ed2,gp_Pln())\n",
    "    f.Perform(radius)\n",
    "    return f.Result(ed1, ed2)\n",
    "\n",
    "def pipe():\n",
    "    # the points\n",
    "    p1 = gp_Pnt(0,0,0)\n",
    "    p2 = gp_Pnt(0,1,0)\n",
    "    p3 = gp_Pnt(1,2,0)\n",
    "    p4 = gp_Pnt(2,2,0)\n",
    "    # the edges\n",
    "    ed1 = BRepBuilderAPI_MakeEdge(p1,p2).Edge()\n",
    "    ed2 = BRepBuilderAPI_MakeEdge(p2,p3).Edge()\n",
    "    ed3 = BRepBuilderAPI_MakeEdge(p3,p4).Edge()\n",
    "    # inbetween\n",
    "    fillet12 = filletEdges(ed1, ed2)\n",
    "    fillet23 = filletEdges(ed2, ed3) \n",
    "    # the wire\n",
    "    makeWire = BRepBuilderAPI_MakeWire()\n",
    "    makeWire.Add(ed1)\n",
    "    makeWire.Add(fillet12)\n",
    "    makeWire.Add(ed2)\n",
    "    makeWire.Add(fillet23)\n",
    "    makeWire.Add(ed3)\n",
    "    makeWire.Build()\n",
    "    wire = makeWire.Wire()\n",
    "    # the pipe\n",
    "    dir = gp_Dir(0,1,0)\n",
    "    circle = gp_Circ(gp_Ax2(p1,dir), 0.2)\n",
    "    profile_edge = BRepBuilderAPI_MakeEdge(circle).Edge()\n",
    "    profile_wire = BRepBuilderAPI_MakeWire(profile_edge).Wire()\n",
    "    profile_face = BRepBuilderAPI_MakeFace(profile_wire).Face()\n",
    "    pipe = BRepOffsetAPI_MakePipe(wire, profile_face).Shape()\n",
    "    display.DisplayShape(pipe, update=True)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    pipe()\n",
    "#    start_display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
